routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /pricing/: members/pricing
  /: home
  # /swift_foundations/:
  #   controller: channel
  #   template: swiftfoundations/index
  #   filter: tag:swift_foundations
  /newsletter/subscribe/: newsletter/subscribe
    template: newsletter/subscribe

collections:
  /lessons/:
    permalink: /lessons/{slug}/
    template: lessons/index
    filter: primary_tag:lesson
  /swift_foundations/:
    permalink: /swift_foundations/{slug}/
    template: swiftfoundations/index
    filter: primary_tag:swift_foundations
  /newsletter/:
    permalink: /newsletter/{slug}/
    template: newsletter/index
    filter: primary_tag:newsletter
    data: tag.newsletter
  /blog/:
    permalink: /blog/{slug}/
    template:
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
