routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /swift_foundations/:
    controller: channel
    template: swiftfoundations/index
    filter: tag:swift_foundations

collections:
  /:
    permalink: /posts/{slug}/
    template:
      - home
  /lessons/:
    permalink: /lessons/{slug}/
    template: /lessons/index
    filter: primary_tag:lesson

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
