routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /: home
  # /swift_foundations/:
  #   controller: channel
  #   template: swiftfoundations/index
  #   filter: tag:swift_foundations

collections:
  /lessons/:
    permalink: /lessons/{slug}/
    template: lessons/index
    filter: primary_tag:lesson
  /swift_foundations/:
    permalink: /swift_foundations/{slug}/
    template: swiftfoundations/index
    filter: primary_tag:swift_foundations
  # /:
  #   permalink: /posts/{slug}/
  #   template:
  #     - index
  /blog/:
    permalink: /blog/{slug}/
    template:
      - index
  /newsletter/:
    permalink: /newsletter/{slug}/
    template: index
    filter: primary_tag:newsletter

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
